version: "3"
services:
  sample_service:
    container_name: bot
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    tty: true
    # secret in /run/secrets/discord_secret.json
    secrets:
      - discord_secret
    volumes:
      - ./src:/app
    command: [ "python", "src/main.py" ]

secrets:
  discord_secret:
    file: .config/discord_secret.json
